name: Keep HF Spaces Awake

on:
  workflow_dispatch: {}       # 手动触发按钮
  schedule:
    - cron: "0 */4 * * *"    # 每 4 小时自动触发

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        url:
          - https://vinceluv-123.hf.space/
          # 可继续添加更多 Space URL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node and Playwright
        run: |
          sudo apt update
          sudo apt install -y npm
          npm init -y
          npm install playwright@latest
          npx playwright install --with-deps chromium

      - name: Ping and Screenshot ${{ matrix.url }}
        run: |
          set -u
          success=true
          summary="### Keep HF Spaces Awake Result for ${{ matrix.url }}\n\n"

          # 将 URL 转成安全 artifact 名称
          safe_name=$(echo "${{ matrix.url }}" | sed 's|[:/]|-|g')

          url_name=$(basename "${{ matrix.url }}")
          screenshot_file="screenshot-${url_name}.png"

          for path in "/" "/?__theme=light"; do
            full_url="${{ matrix.url }}$path"

            if ! curl -A "keepalive-bot/1.0" -sSL --fail --max-time 60 --retry 3 --retry-delay 5 "$full_url" > /dev/null; then
              echo "❌ Request to $full_url failed"
              summary="$summary❌ Request to $full_url failed\n"
              success=false
              break
            else
              echo "✅ Request to $full_url succeeded"
              summary="$summary✅ Request to $full_url succeeded\n"
              node screenshot.js "$full_url" "$screenshot_file"
            fi
          done

          echo -e "$summary" >> $GITHUB_STEP_SUMMARY

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: hf-screenshots-${{ matrix.url | replace(':','-') | replace('/','-') }}
          path: screenshot-*.png

      - name: Add screenshot links to summary
        run: |
          # 将 URL 转成安全 artifact 名称
          safe_name=$(echo "${{ matrix.url }}" | sed 's|[:/]|-|g')
          summary="### Screenshot Links\n"
          for f in screenshot-*.png; do
            name=$(basename "$f")
            summary="$summary\n[View $name](https://github.com/${GITHUB_REPOSITORY}/suites/${GITHUB_RUN_ID}/artifacts)"
          done
          echo -e "$summary" >> $GITHUB_STEP_SUMMARY
