name: Keep HF Spaces Awake

on:
  workflow_dispatch: {}       # 手动触发按钮
  schedule:
    - cron: "0 */4 * * *"    # 每 4 小时自动触发

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        url:
          - https://vinceluv-123.hf.space/
          # 可添加更多 Space URL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node and Playwright
        run: |
          sudo apt update
          sudo apt install -y npm
          npm init -y
          npm install playwright@latest
          npx playwright install --with-deps chromium

      - name: Ping and Screenshot ${{ matrix.url }}
        run: |
          set -u
          success=true
          summary="### Keep HF Spaces Awake Result for ${{ matrix.url }}\n\n"

          url_name=$(basename "${{ matrix.url }}")
          screenshot_file="screenshot-${url_name}.png"

          for path in "/" "/?__theme=light"; do
            full_url="${{ matrix.url }}$path"

            if ! curl -A "keepalive-bot/1.0" -sSL --fail --max-time 60 --retry 3 --retry-delay 5 "$full_url" > /dev/null; then
              echo "❌ Request to $full_url failed"
              summary="$summary❌ Request to $full_url failed\n"
              success=false
              break
            else
              echo "✅ Request to $full_url succeeded"
              summary="$summary✅ Request to $full_url succeeded\n"

              # 调用仓库根目录的 screenshot.js
              node screenshot.js "$full_url" "$screenshot_file"

              # 将截图转 base64 并嵌入 summary
              b64=$(base64 -w 0 "$screenshot_file")
              summary="$summary\n<img src=\"data:image/png;base64,$b64\" width=\"400px\" />\n"
            fi
          done

          # 输出最终 summary
          if [ "$success" = true ]; then
            summary="$summary\n**Final Result:** ✅ All requests succeeded\n"
            echo -e "$summary" >> $GITHUB_STEP_SUMMARY
          else
            summary="$summary\n**Final Result:** ❌ Some requests failed\n"
            echo -e "$summary" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
