name: Keep HF Spaces Awake

on:
  schedule:
    - cron: "0 */4 * * *"   # every 4 hours (GitHub Actions uses UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        url:
          - https://vinceluv-000.hf.space/

    steps:
      - name: Ping ${{ matrix.url }}
        run: |
          set -u
          success=true
          summary="### Keep HF Spaces Awake Result\n\n"

          for path in "/" "/?__theme=light"; do
            if ! curl -A "keepalive-bot/1.0" -sSL --fail --max-time 60 --retry 3 --retry-delay 5 "${{ matrix.url }}$path" > /dev/null; then
              echo "❌ Request to ${{ matrix.url }}$path failed"
              summary="$summary❌ Request to ${{ matrix.url }}$path failed\n"
              success=false
              break
            else
              echo "✅ Request to ${{ matrix.url }}$path succeeded"
              summary="$summary✅ Request to ${{ matrix.url }}$path succeeded\n"
            fi
          done

          if [ "$success" = true ]; then
            summary="$summary\n**Final Result:** ✅ All requests succeeded\n"
            echo -e "$summary" >> $GITHUB_STEP_SUMMARY
          else
            summary="$summary\n**Final Result:** ❌ Some requests failed\n"
            echo -e "$summary" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
